#!/bin/sh

set -e

# Guile has no option to append a directory to a load path.
while getopts A:I:l: option; do
  case $option in
  A | I)
    options="$options -L $OPTARG"
    ;;
  l)
    cp $OPTARG ${OPTARG%.scm}.sld
    ;;
  esac
done

shift $(expr $OPTIND - 1)

LC_ALL=en_US.UTF-8 guile --r7rs -L . $options "$@"
