version: 2
default:
  schedule: &schedule
    interval: daily
    time: 01:00
    timezone: America/Vancouver
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    <<: *default
  - package-ecosystem: gitsubmodule
    directory: /
    <<: *default
  - package-ecosystem: cargo
    directories:
      - /
      - /cmd/minimal
    <<: *default
  - package-ecosystem: gomod
    directory: /
    <<: *default
  - package-ecosystem: npm
    directory: /
    groups:
      astro:
        patterns:
          - astro
          - "@astrojs/*"
    <<: *default
