name: stak/setup
description: Sets up a build environment for Stak Scheme
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: raviqqe/cargo-cache@317322b53633417f67a46d1134375b837712c7a2 # v1.6.4
    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: stable
    - uses: homebrew/actions/setup-homebrew@50b8c2ab4a835c38897ed2c56c293b07167c0b59 # main
      with:
        stable: true
    - run: tools/ci/setup.sh
      shell: bash
