#!/bin/sh

set -e

while getopts l: option; do
  case $option in
  l)
    libraries="$libraries -m ${OPTARG%.scm}"
    ;;
  esac
done

shift $(expr $OPTIND - 1)

main_file=$1
shift 1

chibi-scheme -I . $libraries $main_file "$@"
