#!/bin/sh

set -e

while getopts A:I:l: option; do
  case $option in
  A)
    options="$options -A $OPTARG"
    ;;
  I)
    options="$options -I $OPTARG"
    ;;
  l)
    cp $OPTARG ${OPTARG%.scm}.sld
    ;;
  esac
done

shift $(expr $OPTIND - 1)

chibi-scheme $options "$@"
