#!/bin/sh

set -e

while getopts A:I:l: option; do
  case $option in
  A | I)
    options="$options -$option $OPTARG"
    ;;
  l)
    cp $OPTARG ${OPTARG%.scm}.sld
    ;;
  esac
done

shift $(expr $OPTIND - 1)

chibi-scheme $options "$@"
