#!/bin/sh

set -e

directory=$(dirname $0)/../../..

export PATH=$directory/target/release:$PATH

cat $directory/prelude.scm "$@" | stak-compile >main.out
stak-decode <main.out >/dev/null
stak main.out
