#!/bin/sh

set -e

directory=$(dirname $0)/../../..

compile() {
  if [ $STAK_HOST_INTERPRETER = stak ]; then
    stak-compile
  else
    ${STAK_HOST_INTERPRETER:-gosh} $directory/compile.scm
  fi
}

export PATH=$directory/target/release:$PATH

cat $directory/prelude.scm "$@" | compile >main.out
stak-decode <main.out >/dev/null
stak-interpret main.out
