#!/bin/sh

set -e

directory=$(dirname $0)/../../..

compile() {
  if [ -n "$STAK_HOST_INTERPRETER" ]; then
    $STAK_HOST_INTERPRETER $directory/compile.scm
  else
    stak-compile
  fi
}

profile=debug

if [ -z "$STAK_DEBUG" ]; then
  profile=release
fi

export PATH=$directory/target/$profile:$PATH

cat $directory/prelude.scm "$@" | compile >main.out
stak-decode <main.out >/dev/null
stak-interpret main.out
