#!/bin/sh

set -e

while getopts A:I:l: option; do
  case $option in
  A | I)
    options="$options -$option $OPTARG"
    ;;
  l)
    libraries="$libraries $OPTARG"
    ;;
  esac
done

shift $(expr $OPTIND - 1)

main_file=$1
shift 1

cat $libraries $main_file >gosh.scm

gosh $options gosh.scm "$@"
