#!/bin/sh

set -e

directory=$(dirname $0)/../../..
raw_arguments="$@"

compile() {
  if [ -n "$STAK_HOST_INTERPRETER" ]; then
    $STAK_HOST_INTERPRETER $directory/compile.scm
  else
    stak-compile
  fi
}

arguments() {
  echo $raw_arguments | tr ' ' '\n' | grep "$@" '\.scm$'
}

export PATH=$directory/target/release_test:$PATH

cat $directory/prelude.scm $(arguments) | compile >main.bc
stak-decode <main.bc >/dev/null
stak-interpret main.bc $(arguments -v)
