#!/bin/sh

set -e

directory=$(dirname $0)/../../..

compile() {
  if [ -n "$STAK_HOST_INTERPRETER" ]; then
    $STAK_HOST_INTERPRETER $directory/compile.scm
  else
    stak-compile
  fi
}

script=$1
shift 1

export PATH=$directory/target/release_test:$PATH

cat $directory/prelude.scm "$script" | compile >main.bc
stak-decode <main.bc >/dev/null
stak-interpret main.bc "$@"
