#!/bin/sh

set -e

directory=$(dirname $0)/../../..

while getopts A:I:l: option; do
  case $option in
  A)
    load_path_options="$load_path_options -A $OPTARG"
    ;;
  I)
    load_path_options="$load_path_options -I $OPTARG"
    ;;
  l)
    libraries="$libraries $OPTARG"
    ;;
  esac
done

shift $(expr $OPTIND - 1)

script=$1
shift 1

compile() (
  options="$STAK_COMPILE_OPTIONS $load_path_options"

  if [ -n "$STAK_HOST" ]; then
    $STAK_HOST $directory/compile.scm $options
  else
    $directory/target/release_test/stak-compile $options
  fi
)

cat $directory/prelude.scm $libraries $script |
  grep -v '^#!.*' |
  compile >main.bc

stak-interpret main.bc "$@"
