[package]
name = "no-std-no-alloc"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
heapless = "0.9.3"
stak = { path = "../../root", version = "0.12.30", default-features = false }

[build-dependencies]
stak-build = { path = "../../build", version = "0.12.30" }

[lints]
workspace = true
