#!/bin/sh

set -e

directory=$(dirname $0)/../../..

export PATH=$directory/target/release_test:$directory/cmd/minimal/target/release:$PATH

script=$1
shift 1

cat $directory/prelude.scm "$script" | stak-compile >main.bc
mstak-interpret main.bc "$@"
