name: lint
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup
      - run: tools/lint.sh
  rust_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: cargo fmt -- --check
  scheme_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup
      - run: cargo install schemat
      - run: schemat -cv '**/*.scm'
  gherkin_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: go tool gherkin-format -check .
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: streetsidesoftware/cspell-action@d5d910b521ad408f1e7383c24609079f5a88bdca # v8.2.0
        with:
          files: "**/*.{feature,md,rs,scm,sh,toml}"
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup-node
      - run: node --run lint:toml
  unused_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup
      # spell-checker: disable-next-line
      - uses: bnjbvr/cargo-machete@9debef33b1b3f142e69e1818002196b4f76b02cb # v0.9.0
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --verbose --no-progress --accept 200,429 README.md examples/**/*.md
  lint:
    needs:
      - clippy
      - readme
      - rust_format
      - scheme_format
      - gherkin_format
      - spell_check
      - toml
      - unused_dependencies
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          for result in ${{ join(needs.*.result, ' ') }}; do
            [ $result = success ]
          done
