name: lint
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
      - run: tools/lint.sh
  rust_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: cargo fmt -- --check
  scheme_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
      - run: cargo install schemat
      - run: schemat -cv '**/*.scm'
  gherkin_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: go tool gherkin-format -check .
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          files: "**/*.{feature,md,rs,scm,sh,toml}"
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node
      - run: node --run lint:toml
  unused_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
      # spell-checker: disable-next-line
      - uses: bnjbvr/cargo-machete@ac30a525c0a8d163a92d727b3ff079ee3f6ecb08 # v0.9.2
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: raviqqe/markdown-link-check@7cc7ee84bd8a34196095dc004324cd7c134c01f7 # v1.0.5
        with:
          paths: README.md examples/**/*.md
  lint:
    needs:
      - clippy
      - readme
      - rust_format
      - scheme_format
      - gherkin_format
      - spell_check
      - toml
      - unused_dependencies
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          for result in ${{ join(needs.*.result, ' ') }}; do
            [ $result = success ]
          done
