[package]
name = "stak-lzss"
version.workspace = true
edition.workspace = true
description = "LZSS compression for Stak Scheme"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "stak-lzss"
required-features = ["cli"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = "1.4.1"
quickcheck = "1.1.0"
quickcheck_macros = "1.2.0"

[features]
cli = ["dep:clap"]

[lints]
workspace = true
